---
title: "GATHER Compliance"
bibliography: gather.bib
output:
  pdf_document:
    number_sections: true
    df_print: kable
    toc: true
  html_notebook:
    number_section: true
    toc: true
---

From `r system("git config --get remote.origin.url", intern = TRUE)`
on `r date()`, generated by `r Sys.info()[["effective_user"]]`.

# Overview

This is the GATHER compliance checklist for the paper,
_Measuring the accuracy of gridded human population density surfaces: a case
study in Bioko Island, Equatorial Guinea_
[@stevens2016guidelines]. This checklist summarizes data and methods in order
to be transparent. It's intended for global health audiences but is general enough
to offer some clarity for this paper.


# Checklist

1. Define the indicator(s), populations (including age, sex, and geographic entities), and time period(s)
for which estimates were made. - The study area is Bioko Island, Equatorial Guinea. The Bioko
Island data is 2018. LandScan data is 2018. WorldPop Unconstrained is the 2018 version. WorldPop Constrained is for 2020, so we adjusted it with caveats. HRSL is current, which
makes it a 2019 version, but it assigns numbers from census data, which is older.
The age and sex are all ages and all sexes. It's a total population count.

2. List the funding sources for the work. - Bill and Melinda Gates Foundation BMGF OPP1110495
for the analysis done here. That's separate from funding for the Bioko Island Malaria
Elimination Project that collected this data. BIMEP lists donors on its website:
https://www.mcdinternational.org/donors.

3. Describe how the data were identified and how the data were accessed. - The BIMEP GPS-level data
was critical to a previous collaboration among IHME, BIMEP, and other organizations in order
to estimate malaria prevalence on Bioko Island.

Gridded datasets were included if a) they were publicly available b) they cover
most of Africa c) for the last five years, and d) they include spatial
information at a subnational level.

* Included datasets
  - LandScan from ORNL
  - WorldPop's Constrained and Unconstrained datasets
  - Facebook and CIESIN's High resolution settlement layer
  - Gridded Population of the World (GPWv4.11).

* Excluded datasets of note
  - ESRI's World Population Estimate, because it is commercial.
  - Global Rural-Urban Mapping Project (GRUMPv1), because it covers 1990-2000 only.
  - JRC's European GHS Population Grid, because it is superseded by GPW.
  - U.S. Census Bureaus's country grids (Demobase). This covers only three countries: Haiti, South Sudan, and Pakistan.

4. Specify the inclusion and exclusion criteria. Identify all ad-hoc exclusions.
The gridded maps chosen are all those public
maps which mostly cover Africa. The HRSL, in particular, excludes South Sudan for ethical reasons,
but otherwise covers Africa. We excluded the Gridded Population of the World
because it is directly from census data, so it will be constant across Bioko,
by design.

5. Provide information about all included data sources and their main characteristics.

   a) BIMEP GPS data. This data is not public because it's house-level GPS coordinates.
      Source is the Bioko Island Malaria Elimination Project, part of
      MCDI. Their contact information is MCD International Office,
      8401 Colesville Rd, Suite 425, Silver Spring, MD 20910, P: 301-562-1920,
      F: 301-562-1921, Email: mcdi@mcd.org.

   b) WorldPop. Direct download.
      ftp://ftp.worldpop.org.uk/GIS/Population/Individual_countries/GNQ/Equatorial_Guinea_100m_Population.7z
      
   c) HRSL. Direct download:
      https://ciesin.columbia.edu/repository/hrsl/hrsl_gin_v1.zip
      
   d) LandScan. You have to register on their website. The data is called "LandScan Global 2018."
      https://landscan.ornl.gov/landscan-datasets
   
6. Identify data that have potentially important biases. - The BIMEP data covers 88% of
   households, not 100%. The missing 12% isn't geographically biased. It's from people not
   being home when they checked several times. People tend to move seasonally for work,
   so undercounting people in houses is less of an undercount for the actual number of
   people. We chose to use the data as is.

7. Describe and give sources for any other data inputs. - There is a shapefile for
   Bioko island, constructed by island administration. We could equally well use
   the GADM shapefile for Equatorial Guinea. We use this to define island boundaries.
   We noticed that the island boundaries for LandScan and WorldPop had more area near
   the Southwest shoreline. It was less than one percent, and we went with the Bioko map
   because it is supported by GPS coordinates of houses.

8. Provide all input datasets in a format which can be extracted. - We've handled this by
   providing the code we used to do the calculation. That code will automatically download
   all of the data except the BIMEP GPS data and the Bioko shapefile. It's unfortunately
   not enough for someone else to rerun this code, but it is the exact code that created
   the outputs.

9. Provide a conceptual overview of the data analysis method. The paper text is about
   the analysis method.

10. Provide a detailed description of all steps. The paper is exactly about the math of
    the steps, but it's also provided in the code we make available.
    
11. Describe how candidate models were evaluated and the final models selected.
    This seems more for statistical models. We did do some work to evaluate what should
    be the goodness-of-fit ratio. We settled on the final choice of sum-of-squared-errors
    divided by gold standard variance because it most resembles relative error,
    which is (observed - measured) / measured. So that made sense. This work is in the
    repository as "gofr_comparison.pdf."
    
12. Provide results of an evaluation of model performance. -
    Contained in the paper's results section.

13. Describe methods of calculating uncertainty of the estimates. - There is a section
    of the supplement that looks at uncertainty in point estimates due to
    exact grid location. Each gridded map serves as a realization of a population.
    The map comparison is a demonstration of uncertainty.

14. State how analytic or statistical source code can be accessed. - The
    code is in a public repository at this web address:
    https://github.com/dd-harp/population_comparison_bioko.

15. Provide published estimates in a file from which it can be extracted. -
    These are on the github, for the tables. They are in the vignettes directory
    under summary_statistics.csv, gofr_table.csv, and accuracy.csv.

16. Report quantitative measures of the uncertainty of the estimates. We put those
    into the summary statistics table. That's our best measure, by translating the grid.

17. Interpret results in light of existing evidence. - In the paper.

18. Discuss limitations on estimates. - In the paper's last section.




# Bibliography
