
# GADM Shapefiles for Equatorial Guinea.
gadm36_GNQ_2_sf.rds:
	curl -o gadm36_GNQ_2_sf.rds https://data.biogeo.ucdavis.edu/data/gadm3.6/Rsf/gadm36_GNQ_2_sf.rds

gadm36_GNQ_shp.zip:
	curl -o gadm36_GNQ_shp.zip https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_GNQ_shp.zip

# Settlement layer from https://www.ciesin.columbia.edu/data/hrsl/
# This country is not yet on the public site, which is listed above.


# Worldpop
Equatorial_Guinea_100m_Population.7z:
	curl -o Equatorial_Guinea_100m_Population.7z ftp://ftp.worldpop.org.uk/GIS/Population/Individual_countries/GNQ/Equatorial_Guinea_100m_Population.7z

# Landscan requires an account and approval, which may take a few days.
